// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Sac struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	UserName  string             `json:"user_name"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
