// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateSAC(ctx context.Context, arg CreateSACParams) (Sac, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
