// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createSAC = `-- name: CreateSAC :one
INSERT INTO sacs (
    user_id, message
) VALUES ($1, $2) RETURNING id, user_id, message, created_at
`

type CreateSACParams struct {
	UserID  int64  `json:"user_id"`
	Message string `json:"message"`
}

func (q *Queries) CreateSAC(ctx context.Context, arg CreateSACParams) (Sac, error) {
	row := q.db.QueryRow(ctx, createSAC, arg.UserID, arg.Message)
	var i Sac
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, user_name, first_name, last_name
) VALUES ($1, $2, $3, $4) RETURNING id, user_name, first_name, last_name, created_at
`

type CreateUserParams struct {
	ID        int64  `json:"id"`
	UserName  string `json:"user_name"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.UserName,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, user_name, first_name, last_name, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}
